### ISSUE TITLE
Project Progress Report

### ISSUE THREAD

**Issue by sielerjm** [sielerjm/Plug-n-Chug-Microbiome-16S-Data-Analysis#2]

**Comment by Medelinkant** [comment]
Sounds like you've made nice progress being over halfway through your goals for the term. Mysterious coding problems can be so frustrating! Hope you're able to find a solution soon.

**Comment by BenjaminDalziel** [comment]
1. I really like the principled approach to identifying variables and combinations of them, using a mixture of scripts developed for that purpose, and Rmarkdowns that 'present' the info 
2. I'm curious about an aspect of the science here: how you are handling false discovery risks here / 'p-hacking'?

**Comment by dymite** [comment]
Great work, michael! Your progress thus far is super impressive. I relate to the challenge of redundancy in code... I feel like it has taken me way too long to appreciate the utility of creating even very simple functions to replace things that I do all the time (: Keep kicking ass!

**Comment by varyl97** [comment]
Great job! I really liked your table of completed, in progress, and unfinished tasks. It looks like you're well on your way and I hope you find a solution to that code bug relatively painlessly!

**Comment by cheyennejarman** [comment]
It looks like you are making good time with your project and I really like your tracking board. Excited to see the end results!

**Comment by maddie-hicks** [comment]
I've also found it helpful to insert error checks throughout code to catch issues before they become a problem.  Sounds like you're doing a great job!

**Comment by ssidder** [comment]
I've been experiencing some similarly weird issues with functions and names... what I've tried doing is just renaming the variable in the function to no be something that is a global variable and something that is more descriptive. You've probably tried that work around, but it is what I had to do in order to get a function that was published in a package (and I had used previously in a different script) to work within a piped workflow.

**Comment by JustinHockett** [comment]
It seems like you have a very specific goal in mind and you have been making good progress implementing it, so great job!

**Comment by sielerjm** [comment]
>     1. I really like the principled approach to identifying variables and combinations of them, using a mixture of scripts developed for that purpose, and Rmarkdowns that 'present' the info
> 
>     2. I'm curious about an aspect of the science here: how you are handling false discovery risks here / 'p-hacking'?

Hi Ben,

Good question! I glossed over the nitty-gritty statistical stuff in my presentation. To answer your question, yes, I'm making sure to handle multiple tests and FDR. For example, running a GLM on the variables and their interactions, then running a two-way ANOVA test on the results to assess their significance. Mainly though, at this part of my analysis I'm trying to see what sticks and then later coming back to dig deeper to make sure it's in fact interesting and not dubious.
