### ISSUE TITLE
Project Summary

### ISSUE THREAD

**Issue by sielerjm** [sielerjm/Plug-n-Chug-Microbiome-16S-Data-Analysis#3]

**Comment by cheyennejarman** [comment]
Really cool to see your results! I fully relate to the code frustration but it looks like it is really coming together!

**Comment by kjtonra** [comment]
Nice violin plots! I'm working on some for a paper right now and seeing your finished ones is good motivation. I can tell you've made a lot of progress this quarter- it's a super interesting project and congrats on wrapping up!
